### ISSUE TITLE
Site name not being accepted

### ISSUE THREAD

**Issue by beenish-iftikhar** [scallybrian/OpenFromTableauServer#1]
I get an error when I run the wrokflow. Error: Open From Tableau Server (1): Tool #151: Parse Error at char(28): Unknown variable "site_id" (Expression #1).  Can you see what could be the issue?

**Comment by scallybrian** [comment]
> I get an error when I run the wrokflow. Error: Open From Tableau Server (1): Tool #151: Parse Error at char(28): Unknown variable "site_id" (Expression #1).  Can you see what could be the issue?
> 

Hi, it could be a couple of things. First, have you taken the site name from the server URL (not the alias from the site menu)? There is an example in the readme. If it is the default site you should leave the Site field blank.

What version of Tableau Server are you running?
