### ISSUE TITLE
Tool does not work for Alteryx 2019.4 

### ISSUE THREAD

**Issue by ivanssantos** [scallybrian/OpenFromTableauServer#3]
The Tool does not work for 2019.4.8 as indicated in the description. 
"The tool requires Alteryx Designer 2019.4 or later, and Tableau Server 2018.1 or later."
![image](https://user-images.githubusercontent.com/62585113/120702727-6a1cd880-c482-11eb-8df3-cd39f32c475b.png)

**Comment by scallybrian** [comment]
Thanks, I have updated my documentation accordingly
