### ISSUE TITLE
Readme contains wrong Alteryx Designer version requirement

### ISSUE THREAD

**Issue by jwissehr47** [scallybrian/OpenFromTableauServer#4]
The readme says that the tool requires Alteryx Designer 2020.2 or later.  However, after I installed it I got an error saying that the workflow requires a higher version of Alteryx (2021.2).  When I upgraded to 2021.2 instead of 2020.2 I didn't get the error.

**Comment by scallybrian** [comment]
Thanks - have updated the Alteryx version in the xml of the macros, so should work with 2020.2 onwards without error
